# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "This is my first pipeline"
  displayName: 'Terraform Pipeline'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    allowTelemetryCollection: true