trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
- stage: init
  jobs:
  - job: First
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: ls -l
      displayName: 'Run a multi-line script'
  - job: second
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: ls -l
      displayName: 'Run a multi-line script'
