trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
- job: First
  steps:
 - script: echo Hello, world!
   displayName: 'Run a one-line script'

 - script: ls -l
   displayName: 'Run a multi-line script'
